
import { User, UserRole, UserStatus } from './types';

export const users: User[] = [
  {
    id: 'usr_admin',
    name: 'عبدالله محمد',
    email: 'admin@bokra.hr',
    role: UserRole.SYSTEM_ADMINISTRATOR,
    avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026704d',
    avatarInitials: 'عم',
    jobTitle: 'مسؤول النظام',
    department: 'تكنولوجيا المعلومات',
    status: UserStatus.ACTIVE,
  },
  {
    id: 'usr_board_member',
    name: 'فاطمة علي',
    email: 'board@bokra.hr',
    role: UserRole.BOARD_MEMBER,
    avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026709d',
    avatarInitials: 'فع',
    jobTitle: 'عضو مجلس الإدارة',
    department: 'الإدارة العليا',
    status: UserStatus.ACTIVE,
  },
  {
    id: 'usr_hr_manager',
    name: 'سارة جونسون',
    email: 'hr.manager@bokra.hr',
    role: UserRole.HR_MANAGER,
    avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026705d',
    avatarInitials: 'سج',
    jobTitle: 'مدير الموارد البشرية',
    department: 'الموارد البشرية',
    status: UserStatus.ACTIVE,
  },
  {
    id: 'usr_dept_manager',
    name: 'خالد الغامدي',
    email: 'dept.manager@bokra.hr',
    role: UserRole.DEPARTMENT_MANAGER,
    avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026708d',
    avatarInitials: 'خغ',
    jobTitle: 'مدير قسم التسويق',
    department: 'قسم التسويق',
    status: UserStatus.ACTIVE,
  },
  {
    id: 'usr_branch_manager',
    name: 'يوسف الأحمد',
    email: 'branch.manager@bokra.hr',
    role: UserRole.BRANCH_MANAGER,
    avatar: 'https://i.pravatar.cc/150?u=usr_branch_manager',
    avatarInitials: 'يأ',
    jobTitle: 'مدير فرع جدة',
    department: 'إدارة الفروع',
    status: UserStatus.ACTIVE,
  },
  {
    id: 'usr_hr_employee',
    name: 'إبراهيم حسن',
    email: 'hr.employee@bokra.hr',
    role: UserRole.HR_EMPLOYEE,
    avatar: 'https://i.pravatar.cc/150?u=usr_hr_employee',
    avatarInitials: 'إح',
    jobTitle: 'أخصائي موارد بشرية',
    department: 'الموارد البشرية',
    status: UserStatus.ACTIVE,
  },
  {
    id: 'usr_recruitment_officer',
    name: 'هند سالم',
    email: 'recruitment@bokra.hr',
    role: UserRole.RECRUITMENT_OFFICER,
    avatar: 'https://i.pravatar.cc/150?u=usr_recruitment_officer',
    avatarInitials: 'هس',
    jobTitle: 'مسؤول توظيف',
    department: 'الموارد البشرية',
    status: UserStatus.ACTIVE,
  },
  {
    id: 'usr_employee',
    name: 'أليكس تشين',
    email: 'employee@bokra.hr',
    role: UserRole.EMPLOYEE,
    avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026706d',
    avatarInitials: 'أش',
    jobTitle: 'مطوّر أول',
    department: 'قسم الهندسة',
    status: UserStatus.ACTIVE,
  },
  {
    id: 'usr_trainee',
    name: 'نورة خالد',
    email: 'trainee@bokra.hr',
    role: UserRole.TRAINEE,
    avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026707d',
    avatarInitials: 'نخ',
    jobTitle: 'موظف تحت التمرين',
    department: 'قسم التصميم',
    status: UserStatus.ACTIVE,
  },
  {
    id: 'usr_joker',
    name: 'عمر الشريف',
    email: 'joker@bokra.hr',
    role: UserRole.JOKER_EMPLOYEE,
    avatar: 'https://i.pravatar.cc/150?u=usr_joker',
    avatarInitials: 'عش',
    jobTitle: 'مهام خاصة',
    department: 'جميع الأقسام',
    status: UserStatus.ACTIVE,
  },
];