import { JobPosting, Candidate, JobStatus, HiringStage, CandidateActivity } from '../../types';

export const jobPostings: JobPosting[] = [
    {
        id: 'JOB001',
        title: 'Senior Frontend Engineer',
        department: 'قسم الهندسة',
        status: JobStatus.ACTIVE,
        applicantsCount: 47,
        postedDate: 'May 15, 2024',
    },
    {
        id: 'JOB002',
        title: 'Marketing Manager',
        department: 'قسم التسويق',
        status: JobStatus.ACTIVE,
        applicantsCount: 23,
        postedDate: 'May 20, 2024',
    },
    {
        id: 'JOB003',
        title: 'UX/UI Designer',
        department: 'قسم التصميم',
        status: JobStatus.ON_HOLD,
        applicantsCount: 35,
        postedDate: 'May 10, 2024',
    },
    {
        id: 'JOB004',
        title: 'Sales Representative',
        department: 'قسم المبيعات',
        status: JobStatus.CLOSED,
        applicantsCount: 112,
        postedDate: 'Apr 25, 2024',
    },
];

const sampleActivities1: CandidateActivity[] = [
    { id: 'act1', activity: 'تم نقل المرشح إلى مرحلة الفرز', date: 'June 02, 2024', user: 'مسؤول التوظيف' },
    { id: 'act2', activity: 'تمت مراجعة السيرة الذاتية', date: 'June 03, 2024', notes: 'خبرة قوية في React و TypeScript.', user: 'مسؤول التوظيف' },
    { id: 'act3', activity: 'تم نقل المرشح إلى مرحلة المقابلة', date: 'June 04, 2024', user: 'مدير التوظيف' },
    { id: 'act4', activity: 'تمت جدولة المقابلة الفنية', date: 'June 05, 2024', notes: 'مقابلة مع أحمد محمود يوم 7 يونيو.', user: 'مسؤول التوظيف' },
];

const sampleActivities2: CandidateActivity[] = [
    { id: 'act1', activity: 'تم التقديم على الوظيفة', date: 'June 05, 2024', user: 'النظام' },
];

const sampleActivities3: CandidateActivity[] = [
    { id: 'act1', activity: 'تم التقديم على الوظيفة', date: 'June 02, 2024', user: 'النظام' },
    { id: 'act2', activity: 'تم نقل المرشح إلى مرحلة الفرز', date: 'June 03, 2024', user: 'مسؤول التوظيف' },
];

const sampleActivities4: CandidateActivity[] = [
    { id: 'act1', activity: 'تم التقديم على الوظيفة', date: 'May 28, 2024', user: 'النظام' },
    { id: 'act2', activity: 'تم نقله إلى المقابلة النهائية', date: 'June 01, 2024', user: 'مدير التوظيف' },
    { id: 'act3', activity: 'تم إرسال العرض الوظيفي', date: 'June 03, 2024', notes: 'في انتظار رد المرشح.', user: 'مسؤول التوظيف' },
];


export const candidates: Candidate[] = [
    {
        id: 'CAN001',
        name: 'أحمد محمود',
        avatar: 'https://i.pravatar.cc/150?u=CAN001',
        avatarInitials: 'أم',
        avatarColor: 'bg-blue-500',
        positionApplied: 'Senior Frontend Engineer',
        stage: HiringStage.INTERVIEW,
        appliedDate: 'June 01, 2024',
        email: 'ahmed.m@example.com',
        phone: '+966 50 123 4567',
        resumeUrl: '#',
        skills: ['React', 'TypeScript', 'Node.js', 'GraphQL', 'Webpack'],
        aiSummary: 'مرشح قوي يتمتع بخبرة تزيد عن 5 سنوات في تطوير الواجهات الأمامية باستخدام React و TypeScript. أظهر قدرة على قيادة المشاريع الصغيرة وتسليمها بنجاح. يوصى به بشدة للمقابلة الفنية.',
        activities: sampleActivities1,
    },
    {
        id: 'CAN002',
        name: 'فاطمة الزهراء',
        avatar: 'https://i.pravatar.cc/150?u=CAN002',
        avatarInitials: 'فز',
        avatarColor: 'bg-pink-500',
        positionApplied: 'Marketing Manager',
        stage: HiringStage.APPLIED,
        appliedDate: 'June 05, 2024',
        email: 'fatima.z@example.com',
        phone: '+966 50 234 5678',
        resumeUrl: '#',
        skills: ['SEO', 'Content Marketing', 'Social Media', 'Google Analytics'],
        aiSummary: 'متقدمة حديثة لوظيفة مدير تسويق. السيرة الذاتية تظهر خبرة في التسويق الرقمي وإدارة الحملات. تحتاج إلى فرز أولي لتقييم مدى ملاءمتها للمتطلبات.',
        activities: sampleActivities2,
    },
    {
        id: 'CAN003',
        name: 'خالد عبد العزيز',
        avatar: 'https://i.pravatar.cc/150?u=CAN003',
        avatarInitials: 'خع',
        avatarColor: 'bg-green-500',
        positionApplied: 'Senior Frontend Engineer',
        stage: HiringStage.SCREENING,
        appliedDate: 'June 02, 2024',
        email: 'khaled.a@example.com',
        phone: '+966 50 345 6789',
        resumeUrl: '#',
        skills: ['Vue.js', 'JavaScript', 'CSS', 'HTML5'],
        aiSummary: 'مرشح بخبرة متوسطة في Vue.js. يفتقر إلى بعض المهارات المتقدمة المطلوبة في الوصف الوظيفي ولكنه يظهر إمكانات تعلم جيدة. قد يكون مناسبًا لدور مبتدئ أكثر.',
        activities: sampleActivities3,
    },
    {
        id: 'CAN004',
        name: 'سارة إبراهيم',
        avatar: 'https://i.pravatar.cc/150?u=CAN004',
        avatarInitials: 'سإ',
        avatarColor: 'bg-purple-500',
        positionApplied: 'UX/UI Designer',
        stage: HiringStage.OFFER,
        appliedDate: 'May 28, 2024',
        email: 'sara.i@example.com',
        phone: '+966 50 456 7890',
        resumeUrl: '#',
        skills: ['Figma', 'Sketch', 'Adobe XD', 'User Research', 'Prototyping'],
        aiSummary: 'مصممة UX/UI موهوبة مع مجموعة أعمال قوية تظهر فهمًا عميقًا لمبادئ التصميم التي تركز على المستخدم. أداء ممتاز في جميع مراحل المقابلة. تم تقديم عرض وظيفي.',
        activities: sampleActivities4,
    },
    {
        id: 'CAN005',
        name: 'محمد علي',
        avatar: 'https://i.pravatar.cc/150?u=CAN005',
        avatarInitials: 'مع',
        avatarColor: 'bg-indigo-500',
        positionApplied: 'Marketing Manager',
        stage: HiringStage.SCREENING,
        appliedDate: 'June 04, 2024',
        email: 'mohamed.a@example.com',
        phone: '+966 50 567 8901',
        resumeUrl: '#',
        skills: ['Email Marketing', 'PPC', 'Marketing Automation', 'CRM'],
        aiSummary: 'مرشح ذو خبرة في التسويق عبر البريد الإلكتروني والأتمتة. السيرة الذاتية منظمة بشكل جيد وتظهر نتائج قابلة للقياس. مرشح جيد للمتابعة.',
        activities: sampleActivities3,
    },
    {
        id: 'CAN006',
        name: 'علي حسن',
        avatar: 'https://i.pravatar.cc/150?u=CAN006',
        avatarInitials: 'عح',
        avatarColor: 'bg-red-500',
        positionApplied: 'Sales Representative',
        stage: HiringStage.HIRED,
        appliedDate: 'May 15, 2024',
        email: 'ali.h@example.com',
        phone: '+966 50 678 9012',
        resumeUrl: '#',
        skills: ['Negotiation', 'Salesforce', 'Closing', 'Lead Generation'],
        aiSummary: 'مندوب مبيعات ناجح بسجل حافل من تحقيق وتجاوز الأهداف. تم توظيفه ويبدأ في 1 يوليو.',
        activities: [{ id: 'act1', activity: 'تم التوظيف', date: 'June 10, 2024', user: 'مدير الموارد البشرية' }],
    },
     {
        id: 'CAN007',
        name: 'نور القحطاني',
        avatar: 'https://i.pravatar.cc/150?u=CAN007',
        avatarInitials: 'نق',
        avatarColor: 'bg-yellow-500',
        positionApplied: 'Senior Frontend Engineer',
        stage: HiringStage.INTERVIEW,
        appliedDate: 'June 01, 2024',
        email: 'nour.q@example.com',
        phone: '+966 50 789 0123',
        resumeUrl: '#',
        skills: ['Angular', 'RxJS', 'NgRx', 'TypeScript'],
        aiSummary: 'مرشحة قوية متخصصة في Angular. خبرة واسعة في بناء تطبيقات المؤسسات المعقدة. لديها مقابلة فنية مجدولة.',
        activities: sampleActivities1,
    },
];