import { Employee, EmployeeStatus, OnlineStatus, UserRole, EmployeeActivity } from "../../types";

export const employees: Employee[] = [
    {
        id: 'EMP001',
        firstName: 'John',
        lastName: 'Doe',
        avatar: 'https://i.pravatar.cc/150?u=EMP001',
        avatarInitials: 'JD',
        avatarColor: 'bg-blue-500',
        jobTitle: 'Senior Software Engineer',
        department: 'قسم الهندسة',
        branch: 'فرع الرياض الرئيسي',
        status: EmployeeStatus.ACTIVE,
        onlineStatus: OnlineStatus.ONLINE,
        role: UserRole.EMPLOYEE,
        shiftId: 'shift_morning',
        dateOfBirth: '1990-05-15',
        hireDate: '2020-01-10',
        isPersonWithDisability: false,
        maternityLeavesTaken: 0,
    },
    {
        id: 'EMP002',
        firstName: 'Jane',
        lastName: 'Smith',
        avatar: 'https://i.pravatar.cc/150?u=EMP002',
        avatarInitials: 'JS',
        avatarColor: 'bg-purple-500',
        jobTitle: 'Marketing Manager',
        department: 'قسم التسويق',
        branch: 'فرع الرياض الرئيسي',
        status: EmployeeStatus.ACTIVE,
        onlineStatus: OnlineStatus.ONLINE,
        role: UserRole.DEPARTMENT_MANAGER,
        shiftId: 'shift_morning',
        dateOfBirth: '1985-08-20',
        hireDate: '2018-03-12',
        isPersonWithDisability: false,
        maternityLeavesTaken: 2,
    },
    {
        id: 'EMP003',
        firstName: 'Mike',
        lastName: 'Wilson',
        avatar: 'https://i.pravatar.cc/150?u=EMP003',
        avatarInitials: 'MW',
        avatarColor: 'bg-green-500',
        jobTitle: 'Sales Representative',
        department: 'قسم المبيعات',
        branch: 'فرع جدة',
        status: EmployeeStatus.ON_LEAVE,
        onlineStatus: OnlineStatus.AWAY,
        role: UserRole.EMPLOYEE,
        dateOfBirth: '1992-11-30',
        hireDate: '2021-07-22',
        isPersonWithDisability: false,
        maternityLeavesTaken: 0,
    },
    {
        id: 'EMP004',
        firstName: 'Sarah',
        lastName: 'Johnson',
        avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026705d',
        avatarInitials: 'SJ',
        avatarColor: 'bg-red-500',
        jobTitle: 'HR Manager',
        department: 'الموارد البشرية',
        branch: 'فرع الرياض الرئيسي',
        status: EmployeeStatus.ACTIVE,
        onlineStatus: OnlineStatus.ONLINE,
        role: UserRole.HR_MANAGER,
        dateOfBirth: '1982-02-10',
        hireDate: '2012-05-01',
        isPersonWithDisability: false,
        maternityLeavesTaken: 1,
    },
    {
        id: 'EMP005',
        firstName: 'Alex',
        lastName: 'Chen',
        avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026706d',
        avatarInitials: 'AC',
        avatarColor: 'bg-indigo-500',
        jobTitle: 'UX Designer',
        department: 'قسم التصميم',
        branch: 'فرع جدة',
        status: EmployeeStatus.ACTIVE,
        onlineStatus: OnlineStatus.OFFLINE,
        role: UserRole.TRAINEE,
        shiftId: 'shift_evening',
        dateOfBirth: '2008-06-01',
        hireDate: '2024-07-01',
        isPersonWithDisability: false,
        maternityLeavesTaken: 0,
    },
    {
        id: 'EMP006',
        firstName: 'Lisa',
        lastName: 'Brown',
        avatar: 'https://i.pravatar.cc/150?u=EMP006',
        avatarInitials: 'LB',
        avatarColor: 'bg-pink-500',
        jobTitle: 'Financial Analyst',
        department: 'قسم المالية',
        branch: 'فرع الرياض الرئيسي',
        status: EmployeeStatus.ACTIVE,
        onlineStatus: OnlineStatus.ONLINE,
        role: UserRole.JOKER_EMPLOYEE,
        dateOfBirth: '1995-03-25',
        hireDate: '2023-01-15',
        isPersonWithDisability: true,
        maternityLeavesTaken: 0,
    },
    {
        id: 'EMP008',
        firstName: 'سمير',
        lastName: 'صالح',
        avatar: 'https://i.pravatar.cc/150?u=EMP008',
        avatarInitials: 'سص',
        avatarColor: 'bg-cyan-500',
        jobTitle: 'أخصائي تسويق',
        department: 'قسم التسويق',
        branch: 'فرع جدة',
        status: EmployeeStatus.ACTIVE,
        onlineStatus: OnlineStatus.ONLINE,
        role: UserRole.EMPLOYEE,
        shiftId: 'shift_evening',
        dateOfBirth: '1998-09-05',
        hireDate: '2023-10-01',
        isPersonWithDisability: false,
        maternityLeavesTaken: 0,
    },
    // Add new fields to the rest of the employees
    { id: 'EMP009', firstName: 'Omar', lastName: 'Ahmed', avatar: 'https://i.pravatar.cc/150?u=EMP009', avatarInitials: 'OA', avatarColor: 'bg-teal-500', jobTitle: 'Junior Software Engineer', department: 'قسم الهندسة', branch: 'فرع الرياض الرئيسي', status: EmployeeStatus.ACTIVE, onlineStatus: OnlineStatus.ONLINE, role: UserRole.EMPLOYEE, dateOfBirth: '2000-01-01', hireDate: '2024-02-01', isPersonWithDisability: false, maternityLeavesTaken: 0 },
    { id: 'EMP010', firstName: 'Fatima', lastName: 'Khan', avatar: 'https://i.pravatar.cc/150?u=EMP010', avatarInitials: 'FK', avatarColor: 'bg-lime-500', jobTitle: 'Product Manager', department: 'قسم المنتجات', branch: 'فرع الرياض الرئيسي', status: EmployeeStatus.ACTIVE, onlineStatus: OnlineStatus.AWAY, role: UserRole.DEPARTMENT_MANAGER, dateOfBirth: '1988-04-12', hireDate: '2019-06-15', isPersonWithDisability: false, maternityLeavesTaken: 1 },
    { id: 'EMP011', firstName: 'David', lastName: 'Lee', avatar: 'https://i.pravatar.cc/150?u=EMP011', avatarInitials: 'DL', avatarColor: 'bg-amber-500', jobTitle: 'Data Scientist', department: 'قسم الهندسة', branch: 'فرع الرياض الرئيسي', status: EmployeeStatus.ACTIVE, onlineStatus: OnlineStatus.ONLINE, role: UserRole.EMPLOYEE, dateOfBirth: '1993-07-19', hireDate: '2021-09-01', isPersonWithDisability: false, maternityLeavesTaken: 0 },
    { id: 'EMP012', firstName: 'Emily', lastName: 'White', avatar: 'https://i.pravatar.cc/150?u=EMP012', avatarInitials: 'EW', avatarColor: 'bg-rose-500', jobTitle: 'HR Specialist', department: 'الموارد البشرية', branch: 'فرع الرياض الرئيسي', status: EmployeeStatus.ACTIVE, onlineStatus: OnlineStatus.OFFLINE, role: UserRole.HR_EMPLOYEE, dateOfBirth: '1996-12-03', hireDate: '2022-11-20', isPersonWithDisability: false, maternityLeavesTaken: 0 },
    { id: 'EMP013', firstName: 'Chris', lastName: 'Green', avatar: 'https://i.pravatar.cc/150?u=EMP013', avatarInitials: 'CG', avatarColor: 'bg-fuchsia-500', jobTitle: 'DevOps Engineer', department: 'قسم الهندسة', branch: 'فرع الرياض الرئيسي', status: EmployeeStatus.ACTIVE, onlineStatus: OnlineStatus.ONLINE, role: UserRole.EMPLOYEE, dateOfBirth: '1991-10-10', hireDate: '2020-08-18', isPersonWithDisability: false, maternityLeavesTaken: 0 },
    { id: 'EMP014', firstName: 'Maria', lastName: 'Garcia', avatar: 'https://i.pravatar.cc/150?u=EMP014', avatarInitials: 'MG', avatarColor: 'bg-sky-500', jobTitle: 'Content Strategist', department: 'قسم التسويق', branch: 'فرع جدة', status: EmployeeStatus.ON_LEAVE, onlineStatus: OnlineStatus.AWAY, role: UserRole.EMPLOYEE, dateOfBirth: '1994-01-22', hireDate: '2022-03-05', isPersonWithDisability: false, maternityLeavesTaken: 0 },
    { id: 'EMP015', firstName: 'Tom', lastName: 'Harris', avatar: 'https://i.pravatar.cc/150?u=EMP015', avatarInitials: 'TH', avatarColor: 'bg-emerald-500', jobTitle: 'Account Executive', department: 'قسم المبيعات', branch: 'فرع الرياض الرئيسي', status: EmployeeStatus.ACTIVE, onlineStatus: OnlineStatus.ONLINE, role: UserRole.EMPLOYEE, dateOfBirth: '1997-05-14', hireDate: '2023-04-10', isPersonWithDisability: false, maternityLeavesTaken: 0 },
    { id: 'EMP016', firstName: 'Laura', lastName: 'Martinez', avatar: 'https://i.pravatar.cc/150?u=EMP016', avatarInitials: 'LM', avatarColor: 'bg-violet-500', jobTitle: 'Lead Designer', department: 'قسم التصميم', branch: 'فرع الرياض الرئيسي', status: EmployeeStatus.ACTIVE, onlineStatus: OnlineStatus.ONLINE, role: UserRole.EMPLOYEE, dateOfBirth: '1990-08-30', hireDate: '2019-12-01', isPersonWithDisability: false, maternityLeavesTaken: 1 },
    { id: 'EMP017', firstName: 'Kevin', lastName: 'Clark', avatar: 'https://i.pravatar.cc/150?u=EMP017', avatarInitials: 'KC', avatarColor: 'bg-orange-500', jobTitle: 'IT Support Specialist', department: 'تكنولوجيا المعلومات', branch: 'فرع الرياض الرئيسي', status: EmployeeStatus.ACTIVE, onlineStatus: OnlineStatus.OFFLINE, role: UserRole.EMPLOYEE, dateOfBirth: '1999-02-28', hireDate: '2023-09-01', isPersonWithDisability: false, maternityLeavesTaken: 0 },
    { id: 'EMP018', firstName: 'Jessica', lastName: 'Rodriguez', avatar: 'https://i.pravatar.cc/150?u=EMP018', avatarInitials: 'JR', avatarColor: 'bg-yellow-500', jobTitle: 'Recruitment Officer', department: 'الموارد البشرية', branch: 'فرع الرياض الرئيسي', status: EmployeeStatus.ACTIVE, onlineStatus: OnlineStatus.ONLINE, role: UserRole.RECRUITMENT_OFFICER, dateOfBirth: '1995-06-18', hireDate: '2022-08-22', isPersonWithDisability: false, maternityLeavesTaken: 0 },
    { id: 'EMP019', firstName: 'Brian', lastName: 'Walker', avatar: 'https://i.pravatar.cc/150?u=EMP019', avatarInitials: 'BW', avatarColor: 'bg-stone-500', jobTitle: 'Accountant', department: 'قسم المالية', branch: 'فرع الرياض الرئيسي', status: EmployeeStatus.ACTIVE, onlineStatus: OnlineStatus.ONLINE, role: UserRole.EMPLOYEE, dateOfBirth: '1989-11-11', hireDate: '2017-02-20', isPersonWithDisability: false, maternityLeavesTaken: 0 },
    { id: 'EMP020', firstName: 'Nancy', lastName: 'Hall', avatar: 'https://i.pravatar.cc/150?u=EMP020', avatarInitials: 'NH', avatarColor: 'bg-red-500', jobTitle: 'QA Engineer', department: 'قسم الهندسة', branch: 'فرع الرياض الرئيسي', status: EmployeeStatus.ACTIVE, onlineStatus: OnlineStatus.ONLINE, role: UserRole.EMPLOYEE, dateOfBirth: '1992-04-04', hireDate: '2021-05-16', isPersonWithDisability: false, maternityLeavesTaken: 0 },
    { id: 'EMP021', firstName: 'Paul', lastName: 'Allen', avatar: 'https://i.pravatar.cc/150?u=EMP021', avatarInitials: 'PA', avatarColor: 'bg-blue-500', jobTitle: 'Backend Developer', department: 'قسم الهندسة', branch: 'فرع الرياض الرئيسي', status: EmployeeStatus.ACTIVE, onlineStatus: OnlineStatus.ONLINE, role: UserRole.EMPLOYEE, dateOfBirth: '1994-09-09', hireDate: '2020-10-10', isPersonWithDisability: false, maternityLeavesTaken: 0 },
    { id: 'EMP022', firstName: 'Karen', lastName: 'Young', avatar: 'https://i.pravatar.cc/150?u=EMP022', avatarInitials: 'KY', avatarColor: 'bg-purple-500', jobTitle: 'Social Media Manager', department: 'قسم التسويق', branch: 'فرع جدة', status: EmployeeStatus.ON_LEAVE, onlineStatus: OnlineStatus.AWAY, role: UserRole.EMPLOYEE, dateOfBirth: '1996-03-03', hireDate: '2023-01-25', isPersonWithDisability: false, maternityLeavesTaken: 0 },
    { id: 'EMP023', firstName: 'Jason', lastName: 'King', avatar: 'https://i.pravatar.cc/150?u=EMP023', avatarInitials: 'JK', avatarColor: 'bg-green-500', jobTitle: 'Sales Manager', department: 'قسم المبيعات', branch: 'فرع الرياض الرئيسي', status: EmployeeStatus.ACTIVE, onlineStatus: OnlineStatus.ONLINE, role: UserRole.DEPARTMENT_MANAGER, dateOfBirth: '1987-07-07', hireDate: '2016-04-14', isPersonWithDisability: false, maternityLeavesTaken: 0 },
    { id: 'EMP024', firstName: 'Cynthia', lastName: 'Wright', avatar: 'https://i.pravatar.cc/150?u=EMP024', avatarInitials: 'CW', avatarColor: 'bg-red-500', jobTitle: 'Payroll Specialist', department: 'الموارد البشرية', branch: 'فرع الرياض الرئيسي', status: EmployeeStatus.ACTIVE, onlineStatus: OnlineStatus.ONLINE, role: UserRole.HR_EMPLOYEE, dateOfBirth: '1991-05-05', hireDate: '2021-02-15', isPersonWithDisability: false, maternityLeavesTaken: 1 },
    { id: 'EMP025', firstName: 'Steven', lastName: 'Lopez', avatar: 'https://i.pravatar.cc/150?u=EMP025', avatarInitials: 'SL', avatarColor: 'bg-indigo-500', jobTitle: 'Graphic Designer', department: 'قسم التصميم', branch: 'فرع جدة', status: EmployeeStatus.ACTIVE, onlineStatus: OnlineStatus.OFFLINE, role: UserRole.TRAINEE, dateOfBirth: '2009-01-01', hireDate: '2024-08-01', isPersonWithDisability: false, maternityLeavesTaken: 0 },
    { id: 'EMP026', firstName: 'Amanda', lastName: 'Hill', avatar: 'https://i.pravatar.cc/150?u=EMP026', avatarInitials: 'AH', avatarColor: 'bg-pink-500', jobTitle: 'Senior Accountant', department: 'قسم المالية', branch: 'فرع الرياض الرئيسي', status: EmployeeStatus.ACTIVE, onlineStatus: OnlineStatus.ONLINE, role: UserRole.EMPLOYEE, dateOfBirth: '1986-10-20', hireDate: '2013-03-18', isPersonWithDisability: false, maternityLeavesTaken: 0 },
    { id: 'EMP027', firstName: 'Scott', lastName: 'Scott', avatar: 'https://i.pravatar.cc/150?u=EMP027', avatarInitials: 'SS', avatarColor: 'bg-cyan-500', jobTitle: 'Marketing Analyst', department: 'قسم التسويق', branch: 'فرع الدمام', status: EmployeeStatus.ACTIVE, onlineStatus: OnlineStatus.ONLINE, role: UserRole.EMPLOYEE, dateOfBirth: '1998-12-12', hireDate: '2022-06-30', isPersonWithDisability: false, maternityLeavesTaken: 0 },
    { id: 'EMP028', firstName: 'Melissa', lastName: 'Green', avatar: 'https://i.pravatar.cc/150?u=EMP028', avatarInitials: 'MG', avatarColor: 'bg-teal-500', jobTitle: 'Full Stack Engineer', department: 'قسم الهندسة', branch: 'فرع الرياض الرئيسي', status: EmployeeStatus.ACTIVE, onlineStatus: OnlineStatus.ONLINE, role: UserRole.EMPLOYEE, dateOfBirth: '1993-11-23', hireDate: '2021-01-05', isPersonWithDisability: false, maternityLeavesTaken: 0 },
];


export const employeeActivities: EmployeeActivity[] = [
    {
        id: 'act1',
        icon: 'fas fa-check-circle',
        color: 'green',
        title: 'تمت الموافقة على طلب الإجازة',
        description: 'إجازة سنوية من 15 إلى 18 أغسطس',
        timestamp: 'منذ يومين'
    },
    {
        id: 'act2',
        icon: 'fas fa-graduation-cap',
        color: 'blue',
        title: 'أكمل دورة تدريبية',
        description: 'React Advanced Patterns',
        timestamp: 'منذ 5 أيام'
    },
    {
        id: 'act3',
        icon: 'fas fa-file-alt',
        color: 'purple',
        title: 'تم تحديث المستند',
        description: 'تم رفع جواز السفر الجديد',
        timestamp: 'منذ أسبوع'
    },
    {
        id: 'act4',
        icon: 'fas fa-clock',
        color: 'orange',
        title: 'تم تسجيل مخالفة حضور',
        description: 'وصول متأخر (15 دقيقة)',
        timestamp: 'منذ أسبوعين'
    }
];